version: "3.9"

services:

  nginx:
    build:
      context: ./nginx
      args:
        - DEV=true
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - 8000:80
    depends_on:
      - web
    restart: always

  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:5432 &&
             python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/static
      - media:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  media:
  static:
  postgres:
