version: "3.9"

services:

  nginx:
    build:
      context: ./nginx
      args:
        - DEV=false
    volumes:
      - media:/app/media
      - static:/app/static
      - /etc/letsencrypt:/etc/letsencrypt
