version: "3.9"

services:

  nginx:
    build:
      context: ./nginx
      args:
        - DEV=false
    volumes:
      - media:/app/media
      - static:/app/static
      - /etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    
